### ISSUE TITLE
status of growthchart

### ISSUE THREAD

**Issue by cultulhul** [nathanleiby/growthchart#5]
Hey, do you still plan to work on it or is the project dead ]

**Comment by nathanleiby** [comment]
Hello @cultulhul!

I haven't worked on it actively for more than 5 years. Feel free to take
the code and use/edit in any way.

**Comment by cultulhul** [comment]
thanks

**Comment by nathanleiby** [comment]
https://www.reddit.com/r/bodyweightfitness/comments/9zbgar/bwf_daily_discussion_and_beginnerrr_questions/?utm_source=reddit-android
